title: Nasr U Khan's Data Science Portfolio # your name (or website title) here
logo: "logo.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Data Scientist at Lloyds Banking Group, and am very passionate about topics in mathematics, statistics and data science.  
  <br><br>
  <a href="https://www.linkedin.com/in/nasr-u-khan-8973a312a">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
